export interface FormInputData {
    adminName: string,
    adminEmail: string,
    adminPhone: string,
    adminUsername: string,
    adminPassword: string,
    teamName: string,
    teamCnpj: string,
    teamEmail: string,
    teamSuit: string,
    coachName: string,
    coachEmail: string,
    coachPhone: string,
    coachCref: string,
}
